WarehouseReportingWebApp/Controllers/ClaimsController.cs
using System.Web.Mvc;

namespace WarehouseReportingWebApp.Controllers
{
    [Authorize]
    public class ClaimsController : Controller
    {
        /// <summary>
        /// Add user's claims to viewbag
        /// </summary>
        /// <returns></returns>
        public ActionResult Claims()
        {
            var userClaims = User.Identity as System.Security.Claims.ClaimsIdentity;

            //You get the user’s first and last name below:
            ViewBag.Name = userClaims?.FindFirst("name")?.Value;

            // The 'preferred_username' claim can be used for showing the username
            ViewBag.Username = userClaims?.FindFirst("preferred_username")?.Value;

            // The subject/ NameIdentifier claim can be used to uniquely identify the user across the web
            ViewBag.Subject = userClaims?.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;

            // TenantId is the unique Tenant Id - which represents an organization in Azure AD
            ViewBag.TenantId = userClaims?.FindFirst("http://schemas.microsoft.com/identity/claims/tenantid")?.Value;

            return View();
        }
    }
}

WarehouseReportingWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Owin.Security;
using Microsoft.Owin.Security.Cookies;
using Microsoft.Owin.Security.OpenIdConnect;

namespace WarehouseReportingWebApp.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// Send an OpenID Connect sign-in request.
        /// Alternatively, you can just decorate the SignIn method with the [Authorize] attribute
        /// </summary>
        public void SignIn()
        {
            if (!Request.IsAuthenticated)
            {
                HttpContext.GetOwinContext().Authentication.Challenge(
                    new AuthenticationProperties { RedirectUri = "/" },
                    OpenIdConnectAuthenticationDefaults.AuthenticationType);
            }
        }

        /// <summary>
        /// Send an OpenID Connect sign-out request.
        /// </summary>
        public void SignOut()
        {
            HttpContext.GetOwinContext().Authentication.SignOut(
                    OpenIdConnectAuthenticationDefaults.AuthenticationType,
                    CookieAuthenticationDefaults.AuthenticationType);
        }
    }
}

WarehouseReportingWebApp/Controllers/SnowflakeController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Snowflake_Connector;

namespace WarehouseReportingWebApp.Controllers
{
    [Authorize]
    public class SnowflakeController : Controller
    {
        /// <summary>
        /// Add user's claims to viewbag
        /// </summary>
        /// <returns></returns>
        public ActionResult SnowflakeIndex()
        {
            var userClaims = User.Identity as System.Security.Claims.ClaimsIdentity;

            ////You get the user’s first and last name below:
            ViewBag.Name = userClaims?.FindFirst("name")?.Value;

            //// The 'preferred_username' claim can be used for showing the username
            ViewBag.Username = userClaims?.FindFirst("preferred_username")?.Value;

            ViewBag.testResult = new List<string>();

            return View();
        }

        public ActionResult SnowflakeTest()
        {
            ViewBag.testResult = DataConnector.TestConnection();

            return View();
        }
    }
}

WarehouseReportingWebApp/Views/Claims/Claims.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Claims</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>
<body style="padding:50px">
    <h3>Main Claims:</h3>
    <table class="table table-striped table-bordered table-hover">
        <tr><td>Name</td><td>@ViewBag.Name</td></tr>
        <tr><td>Username</td><td>@ViewBag.Username</td></tr>
        <tr><td>Subject</td><td>@ViewBag.Subject</td></tr>
        <tr><td>TenantId</td><td>@ViewBag.TenantId</td></tr>
    </table>
    <br />
    <h3>All Claims:</h3>
    <table class="table table-striped table-bordered table-hover table-condensed">
        @foreach (var claim in System.Security.Claims.ClaimsPrincipal.Current.Claims)
        {
            <tr><td>@claim.Type</td><td>@claim.Value</td></tr>
        }
    </table>
    <br />
    <br />
    @Html.ActionLink("Sign out", "SignOut", "Home", null, new { @class = "btn btn-primary" })
</body>
</html>

WarehouseReportingWebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Data Warehouse Reporting</h2>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Home</title>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
    @if (!Request.IsAuthenticated)
    {
        <!-- If the user is not authenticated, display the sign-in button -->
        //@Html.ActionLink("Sign In", "SignIn", "Home", null, new { @class = "btn btn-primary" })
        <br />
        <a href="@Url.Action("SignIn", "Home")" style="text-decoration: none;">
            <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="300px" height="50px" viewBox="0 0 3278 522" class="SignInButton">
                <style type="text/css">

                    .fil0:hover {
                        fill: #4B4B4B;
                    }

                    .fnt0 {
                        font-size: 260px;
                        font-family: 'Segoe UI Semibold', 'Segoe UI';
                        text-decoration: none;
                    }
                </style>
                <rect class="fil0" x="2" y="2" rx="80" ry="80" width="3174" height="517" fill="black" />
                <rect x="150" y="129" width="122" height="122" fill="#F35325" />
                <rect x="284" y="129" width="122" height="122" fill="#81BC06" />
                <rect x="150" y="263" width="122" height="122" fill="#05A6F0" />
                <rect x="284" y="263" width="122" height="122" fill="#FFBA08" />
                <text x="470" y="357" fill="white" class="fnt0">Sign in with Microsoft</text>
            </svg>
        </a>
    }
    else
    {
        <span><br />Hello @System.Security.Claims.ClaimsPrincipal.Current.FindFirst("name").Value;</span>
        <br /><br />
        @Html.ActionLink("See Your Claims", "Claims", "Claims")
        <br /><br />
        @Html.ActionLink("Snowflake Reports", "SnowflakeIndex", "Snowflake")
        <br /><br />
        @Html.ActionLink("Wallboards", "Index", "Wallboard")
        <br /><br />
        @Html.ActionLink("Sign out", "SignOut", "Home")
    }
    @if (!string.IsNullOrWhiteSpace(Request.QueryString["errormessage"]))
    {
        <div style="background-color:red;color:white;font-weight: bold;">Error: @Request.QueryString["errormessage"]</div>
    }
</body>
</html>

WarehouseReportingWebApp/Views/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Snowflake Reports</h2>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Snowflake Reports</title>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
</head>
<body style="padding:50px">
    <h3>Main Claims:</h3>
    <table class="table table-striped table-bordered table-hover">
        <tr><td>Name</td><td>@ViewBag.Name</td></tr>
        <tr><td>Username</td><td>@ViewBag.Username</td></tr>
        <tr><td>Subject</td><td>@ViewBag.Subject</td></tr>
        <tr><td>TenantId</td><td>@ViewBag.TenantId</td></tr>
    </table>
    <br />
    <h3>All Claims:</h3>
    <table class="table table-striped table-bordered table-hover table-condensed">
        @foreach (var claim in System.Security.Claims.ClaimsPrincipal.Current.Claims)
        {
            <tr><td>@claim.Type</td><td>@claim.Value</td></tr>
        }
    </table>
    <br />
    <br />
    @Html.ActionLink("Sign out", "SignOut", "Home", null, new { @class = "btn btn-primary" })
</body>
</html>

WarehouseReportingWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Data Warehouse Reporting</title>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Data Warehouse Reporting", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="navbar-nav nav">
                    @if (Request.IsAuthenticated)
                    {
                        <!-- If the user is authenticated, display the other buttons -->
                        <li class="nav-item">
                            @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Snowflake", "SnowflakeIndex", "Snowflake", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Wallboards", "Index", "Wallboards", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    }
                </ul>
                <ul class="navbar-nav nav navbar-right">
                    @if (Request.IsAuthenticated)
                    {
                        <!-- If the user is authenticated, display the other buttons -->
                        <li class="nav-item">
                            @Html.ActionLink("Sign out", "SignOut", "Home", null, new { @class = "nav-link" })
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Money Expert</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

WarehouseReportingWebApp/Views/Snowflake/SnowflakeIndex.cshtml
@{
    ViewBag.Title = "SnowflakeIndex";
}

<h2>Snowflake Reports</h2>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Snowflake Reports</title>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
</head>
<body style="padding:50px">
    <h3>Main Claims:</h3>
    <table class="table table-striped table-bordered table-hover">
        <tr><td>Name</td><td>@ViewBag.Name</td></tr>
        <tr><td>Username</td><td>@ViewBag.Username</td></tr>
    </table>
    <br />
    @Html.ActionLink("Run Test", "SnowflakeTest", "Snowflake")
    <table class="table table-striped table-bordered table-hover table-condensed">
        @foreach (var line in ViewBag.testResult)
        {
            <tr><td>@line</td></tr>
        }
    </table>
</body>
</html>